[package]
name = "rust-simple-init"
version = "0.1.0"
authors = ["Nathan Rossi <nathan@nathanrossi.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/nathanrossi/meta-random"

[dependencies]
nix = "0.8.0"
libc = "0.2"
#mio = { version = "0.7", features = ["os-poll", "os-util"] }
mio = { version = "0.6", features = [] }
tokio = { version = "0.2", features = ["rt-core", "io-util", "io-driver", "process", "macros"] }
futures = "0.3"
