[package]
name = "rust-simple-init"
version = "0.1.0"
authors = ["Nathan Rossi <nathan@nathanrossi.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/nathanrossi/meta-random"

[dependencies]
nix = "0.24.1"
libc = "0.2.78"
#mio = { version = "0.7", features = ["os-poll", "os-util"] }
mio = { version = "0.6", features = [] }
futures = "0.3"
